name: merge main
"on":
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --ignore-scripts

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_VITE_API_KEY: "AIzaSyBcYwDA6cCueU8Ld9CnQdn76VKs4hroi30"
          envkey_VITE_AUTH_DOMAIN: "krause-media.firebaseapp.com"
          envkey_VITE_PROJECT_ID: "krause-media"
          envkey_VITE_STORAGE_BUCKET: "krause-media.appspot.com"
          envkey_VITE_MESSAGING_SENDER_ID: "177705104739"
          envkey_VITE_APP_ID: "1:177705104739:web:0ef5a73b806e4a52e20f56"
          envkey_VITE_MEASUREMENT_ID: "G-R49FQ0LX9L"
          file_name: .env

      - run: yarn run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KRAUSE_MEDIA }}"
          channelId: live
          projectId: krause-media
